// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $blog_title_html from "./routes/blog/[title].html.tsx";
import * as $blog_deno_open_telemetry from "./routes/blog/deno_open_telemetry.tsx";
import * as $blog_parameterized_testing_deno from "./routes/blog/parameterized_testing_deno.tsx";
import * as $blogroll from "./routes/blogroll.tsx";
import * as $index from "./routes/index.tsx";
import * as $Analytics from "./islands/Analytics.tsx";
import * as $Comments from "./islands/Comments.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/blog/[title].html.tsx": $blog_title_html,
    "./routes/blog/deno_open_telemetry.tsx": $blog_deno_open_telemetry,
    "./routes/blog/parameterized_testing_deno.tsx":
      $blog_parameterized_testing_deno,
    "./routes/blogroll.tsx": $blogroll,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Analytics.tsx": $Analytics,
    "./islands/Comments.tsx": $Comments,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
