name: Print resume.html to PDF
on:
  push:
    branches: main
    paths:
      - "./static/resume.html"

jobs:
  print:
    name: Print resume
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./static/resume.html
          outputFile: ./resume.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: zach_auten_resume.pdf
          path: ./resume.pdf
